#!/bin/bash
# Loader for RemoteUI python script
# Copyright (C) 2013  Federico "MrModd" Cosentino (http://mrmodd.it/)
#
### BEGIN INIT INFO
# Provides:          remoteui
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Loader for RemoteUI python script
# Description:       Launch RemoteUI python script when Arduino is connected to the system
### END INIT INFO

SHELL="/bin/bash"
SCRIPT="opt/remoteui/remoteui.sh"
PIDFILE="/var/run/remoteui.pid"

case "$1" in
	start)
		echo "Starting RemoteUI service"
		start-stop-daemon --start --verbose --pidfile $PIDFILE --user root --group root -b --make-pidfile --chuid root --exec $SHELL $SCRIPT
		;;
	stop)
		echo "Stopping RemoteUI service"
		start-stop-daemon --stop --pidfile $PIDFILE --verbose
		rm -f $PIDFILE
		;;
	restart)
		echo "Stopping RemoteUI service"
		start-stop-daemon --stop --pidfile $PIDFILE --verbose
		rm -f $PIDFILE
		echo "Starting RemoteUI service"
		start-stop-daemon --start --verbose --pidfile $PIDFILE --user root --group root -b --make-pidfile --chuid root --exec $SHELL $SCRIPT
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
